// ======================
// LOGIN PROTECTION
// ======================

if (localStorage.getItem("isLoggedIn") !== "true") {
    window.location.href = "../LoginPage.html";
}

// ======================
// GO BACK
// ======================

function goBack() {
    window.location.href = "reports.html";
}

// ======================
// GO TO DASHBOARD
// ======================

function goDashboard() {
    window.location.href = "dashboard.html";
}

// ======================
// DOWNLOAD REPORT
// ======================

function downloadReport() {

    const reportData = `
SOUNDPRO SALES REPORT
=====================

Period: May 1 - May 31, 2025

Total Revenue: ₹12,50,000

Top Products:
1. JBL SRX 725 Speaker - ₹12,50,000
2. JBL SRX 715 Speaker - ₹9,80,000
3. JBL Headphone - ₹7,50,000

Growth: +21.8% vs last month

Generated by SoundPro Inventory System
`;

    const blob = new Blob(
        [reportData],
        { type: "text/plain" }
    );

    const link = document.createElement("a");

    link.href = URL.createObjectURL(blob);

    link.download = "SalesReport.txt";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);

    URL.revokeObjectURL(link.href);
}

// ======================
// LOGOUT
// ======================

function logout() {

    const result = confirm(
        "Are you sure you want to logout?"
    );

    if (result) {

        localStorage.removeItem(
            "isLoggedIn"
        );

        window.location.href =
            "../LoginPage.html";
    }
}

// ======================
// PAGE LOAD ANIMATION
// ======================

window.addEventListener("load", () => {

    const cards = document.querySelectorAll(
        ".card, .item, .revenue"
    );

    cards.forEach((card, index) => {

        card.style.opacity = "0";
        card.style.transform =
            "translateY(20px)";

        setTimeout(() => {

            card.style.transition =
                "all 0.4s ease";

            card.style.opacity = "1";

            card.style.transform =
                "translateY(0)";

        }, index * 150);

    });

});

// ======================
// PRODUCT HOVER EFFECT
// ======================

const products =
    document.querySelectorAll(".item");

products.forEach(item => {

    item.addEventListener(
        "mouseenter",
        () => {
            item.style.transform =
                "translateY(-3px)";
        }
    );

    item.addEventListener(
        "mouseleave",
        () => {
            item.style.transform =
                "translateY(0)";
        }
    );

});