// ======================
// LOGIN PROTECTION
// ======================

if (localStorage.getItem("isLoggedIn") !== "true") {
    window.location.href = "../LoginPage.html";
}

// ======================
// GO BACK
// ======================

function goBack() {
    window.location.href = "reports.html";
}

// ======================
// GO TO DASHBOARD
// ======================

function goDashboard() {
    window.location.href = "dashboard.html";
}

// ======================
// LOAD SALES DATA
// ======================

async function loadSalesData() {
    try {
        const res = await fetch('/api/reports/sales');
        const data = await res.json();
        if (!data.success) return;

        const report = data.report;
        const revenueEl = document.querySelector('.revenue h1');
        const dateEl = document.querySelector('.date-box span');

        if (revenueEl) {
            revenueEl.textContent = '₹' + Number(report.totalRevenue).toLocaleString();
        }
        if (dateEl) {
            dateEl.textContent = report.period || 'All time';
        }

        const itemEls = document.querySelectorAll('.item');
        const topRes = await fetch('/api/reports/top-products');
        const topData = await topRes.json();
        if (topData.success && topData.products) {
            itemEls.forEach((item, i) => {
                const p = topData.products[i];
                if (p) {
                    const nameEl = item.querySelector('h4');
                    const priceEl = item.querySelector('span');
                    if (nameEl) nameEl.textContent = p.name;
                    if (priceEl) priceEl.textContent = '₹' + Number(p.price).toLocaleString();
                }
            });
        }

    } catch (err) {
        console.error('Failed to load sales data:', err);
    }
}

// ======================
// DOWNLOAD REPORT
// ======================

async function downloadReport() {
    try {
        const res = await fetch('/api/reports/sales');
        const data = await res.json();
        const report = data.report || {};

        const reportData = `
SOUNDPRO SALES REPORT
=====================

Period: ${report.period || 'All time'}

Total Revenue: ₹${Number(report.totalRevenue).toLocaleString()}
Total Orders: ${report.totalOrders || 0}

Generated by SoundPro Inventory System
`;

        const blob = new Blob(
            [reportData],
            { type: "text/plain" }
        );

        const link = document.createElement("a");
        link.href = URL.createObjectURL(blob);
        link.download = "SalesReport.txt";
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
        URL.revokeObjectURL(link.href);
    } catch (err) {
        console.error('Download report error:', err);
        alert('Failed to generate report. Check server connection.');
    }
}

// ======================
// LOGOUT
// ======================

function logout() {
    const result = confirm("Are you sure you want to logout?");
    if (result) {
        localStorage.removeItem("isLoggedIn");
        window.location.href = "../LoginPage.html";
    }
}

// ======================
// PAGE LOAD
// ======================

window.addEventListener("load", () => {

    loadSalesData();

    const cards = document.querySelectorAll(
        ".card, .item, .revenue"
    );

    cards.forEach((card, index) => {
        card.style.opacity = "0";
        card.style.transform = "translateY(20px)";

        setTimeout(() => {
            card.style.transition = "all 0.4s ease";
            card.style.opacity = "1";
            card.style.transform = "translateY(0)";
        }, index * 150);
    });
});

// ======================
// PRODUCT HOVER EFFECT
// ======================

const products = document.querySelectorAll(".item");

products.forEach(item => {
    item.addEventListener("mouseenter", () => {
        item.style.transform = "translateY(-3px)";
    });

    item.addEventListener("mouseleave", () => {
        item.style.transform = "translateY(0)";
    });
});
